### PR TITLE
Fix #2

### LINKED ISSUE #2: Align elements to the center
Align all the elements in the readme.md file to the center

### PR DESCRIPTION
**Pull request by ghost**
Fix #2

### CODE REVIEW

**Comment by ChinmayMhatre** [comment]
I think just removing the bullet points from the blog post would be better. They are still left aligned

**Comment by ghost** [comment]
I tried to do this. But the layout was breaking. You can see it out: https://github.com/krishdevdb/ChinmayMhatre/tree/4289e54398952d08fd9595f4fdb176f2b309b37e

**Comment by ChinmayMhatre** [comment]
Oh okay!

**Comment by ChinmayMhatre** [comment]
Then I guess this looks good !! Thank you for the contribution!🙌

**Pull request merged**
